EXTRA_DIST = README $(CASES)

clean-local:
	rm -Rf working

CASES = \
	case/test-c-00.c \
	case/test-c-00.ri \
	case/test-c-01.c \
	case/test-c-01.ri \
	case/test-crack-00.crack \
	case/test-crack-00.ri \
	case/test-crack-01.crack \
	case/test-crack-01.ri \
	case/test-csharp-00.csharp \
	case/test-csharp-00.ri \
	case/test-csharp-01.csharp \
	case/test-csharp-01.ri \
	case/test-d-00.d \
	case/test-d-00.ri \
	case/test-d-01.d \
	case/test-d-01.ri \
	case/test-go-00.go \
	case/test-go-00.ri \
	case/test-go-01.go \
	case/test-go-01.ri \
	case/test-go-02.go \
	case/test-go-02.ri \
	case/test-go-03.go \
	case/test-go-03.ri \
	case/test-java-00.java \
	case/test-java-00.ri \
	case/test-java-01.java \
	case/test-java-01.ri \
	case/test-js-00.js \
	case/test-js-00.ri \
	case/test-js-01.js \
	case/test-js-01.ri \
	case/test-julia-00.julia \
	case/test-julia-00.ri \
	case/test-julia-01.julia \
	case/test-julia-01.ri \
	case/test-ocaml-00.ocaml \
	case/test-ocaml-00.ri \
	case/test-ocaml-01.ocaml \
	case/test-ocaml-01.ri \
	case/test-ocaml-02.ocaml \
	case/test-ocaml-02.ri \
	case/test-ruby-00.ri \
	case/test-ruby-00.ruby \
	case/test-ruby-01.ri \
	case/test-ruby-01.ruby \
	case/test-rust-00.ri \
	case/test-rust-00.rust \
	case/test-rust-01.ri \
	case/test-rust-01.rust \
	case/test-zig-00.ri \
	case/test-zig-00.zig \
	case/test-zig-01.ri \
	case/test-zig-01.zig \
	case/test-zig-02.ri \
	case/test-zig-02.zig
